#!/bin/bash

mv "full-preflop-charts-3_1.jpg" "UTG.jpg"
mv "full-preflop-charts-3_2.jpg" "UTG+1.jpg"
mv "full-preflop-charts-3_3.jpg" "UTG+2.jpg"
mv "full-preflop-charts-3_4.jpg" "Lojack.jpg"
mv "full-preflop-charts-3_5.jpg" "Hijack.jpg"
mv "full-preflop-charts-3_6.jpg" "Cutoff.jpg"
mv "full-preflop-charts-3_7.jpg" "Button.jpg"
mv "full-preflop-charts-3_8.jpg" "Small_Blind.jpg"

mv "full-preflop-charts-4_1.jpg" "UTG+1_vs_UTG.jpg"
mv "full-preflop-charts-4_2.jpg" "UTG+2_vs_UTG-UTG+1.jpg"
mv "full-preflop-charts-4_3.jpg" "LJ_vs_UTG-UTG+1.jpg"
mv "full-preflop-charts-4_4.jpg" "LJ_vs_UTG+2.jpg"
mv "full-preflop-charts-4_5.jpg" "HJ_vs_UTG.jpg"
mv "full-preflop-charts-4_6.jpg" "HJ_vs_UTG+1.jpg"
mv "full-preflop-charts-4_7.jpg" "HJ_vs_UTG+2.jpg"
mv "full-preflop-charts-4_8.jpg" "HJ_vs_LJ.jpg"

mv "full-preflop-charts-5_1.jpg" "CO_vs_UTG-UTG+1.jpg"
mv "full-preflop-charts-5_2.jpg" "CO_vs_UTG+2.jpg"
mv "full-preflop-charts-5_3.jpg" "CO_vs_LJ.jpg"
mv "full-preflop-charts-5_4.jpg" "CO_vs_HJ.jpg"

mv "full-preflop-charts-6_1.jpg" "BTN_vs_UTG.jpg"
mv "full-preflop-charts-6_2.jpg" "BTN_vs_UTG+1.jpg"
mv "full-preflop-charts-6_3.jpg" "BTN_vs_UTG+2.jpg"
mv "full-preflop-charts-6_4.jpg" "BTN_vs_LJ.jpg"
mv "full-preflop-charts-6_5.jpg" "BTN_vs_HJ.jpg"
mv "full-preflop-charts-6_6.jpg" "BTN_vs_CO.jpg"

mv "full-preflop-charts-7_1.jpg" "SB_vs_UTG-UTG+1.jpg"
mv "full-preflop-charts-7_2.jpg" "SB_vs_UTG+2.jpg"
mv "full-preflop-charts-7_3.jpg" "SB_vs_LJ.jpg"
mv "full-preflop-charts-7_4.jpg" "SB_vs_HJ.jpg"
mv "full-preflop-charts-7_5.jpg" "SB_vs_CO.jpg"
mv "full-preflop-charts-7_6.jpg" "SB_vs_BTN.jpg"

mv "full-preflop-charts-8_1.jpg" "BB_vs_UTG-UTG+1.jpg"
mv "full-preflop-charts-8_2.jpg" "BB_vs_UTG+2.jpg"
mv "full-preflop-charts-8_3.jpg" "BB_vs_LJ.jpg"
mv "full-preflop-charts-8_4.jpg" "BB_vs_HJ.jpg"
mv "full-preflop-charts-8_5.jpg" "BB_vs_CO.jpg"
mv "full-preflop-charts-8_6.jpg" "BB_vs_BTN.jpg"
mv "full-preflop-charts-8_7.jpg" "BB_vs_SB.jpg"

mv "full-preflop-charts-9_1.jpg" "UTG_RFI_vs_3bet.jpg"
mv "full-preflop-charts-9_2.jpg" "UTG_vs_UTG+1_3bet.jpg"
mv "full-preflop-charts-9_3.jpg" "UTG_vs_UTG+2_3bet.jpg"
mv "full-preflop-charts-9_4.jpg" "UTG_vs_LJ_3bet.jpg"
mv "full-preflop-charts-9_5.jpg" "UTG_vs_HJ_3bet.jpg"
mv "full-preflop-charts-9_6.jpg" "UTG_vs_CO-BTN_3bet.jpg"

mv "full-preflop-charts-10_1.jpg" "UTG+1_RFI_vs_3bet.jpg"
mv "full-preflop-charts-10_2.jpg" "UTG+1_vs_UTG+2_3bet.jpg"
mv "full-preflop-charts-10_3.jpg" "UTG+1_vs_LJ_3bet.jpg"
mv "full-preflop-charts-10_4.jpg" "UTG+1_vs_HJ-CO_3bet.jpg"
mv "full-preflop-charts-10_5.jpg" "UTG+1_vs_BTN_3bet.jpg"

mv "full-preflop-charts-11_1.jpg" "UTG+2_RFI_vs_3bet.jpg"
mv "full-preflop-charts-11_2.jpg" "UTG+2_vs_LJ_3bet.jpg"
mv "full-preflop-charts-11_3.jpg" "UTG+2_vs_HJ_3bet.jpg"
mv "full-preflop-charts-11_4.jpg" "UTG+2_vs_CO-BTN_3bet.jpg"

mv "full-preflop-charts-12_1.jpg" "LJ_RFI_vs_3bet.jpg"
mv "full-preflop-charts-12_2.jpg" "LJ_vs_HJ_3bet.jpg"
mv "full-preflop-charts-12_3.jpg" "LJ_vs_CO_3bet.jpg"
mv "full-preflop-charts-12_4.jpg" "LJ_vs_BTN_3bet.jpg"
mv "full-preflop-charts-12_5.jpg" "LJ_vs_SB_3bet.jpg"

mv "full-preflop-charts-13_1.jpg"  "HJ-CO_RFI_vs_3bet.jpg"
mv "full-preflop-charts-13_2.jpg"  "HJ_vs_CO_3bet.jpg"
mv "full-preflop-charts-13_3.jpg"  "HJ_vs_BTN_3bet.jpg"
mv "full-preflop-charts-13_4.jpg"  "HJ_vs_SB_3bet.jpg"
mv "full-preflop-charts-13_5.jpg"  "HJ_vs_BB_3bet.jpg"
mv "full-preflop-charts-13_6.jpg"  "CO_vs_BTN-SB_3bet.jpg"

mv "full-preflop-charts-14_1.jpg" "BTN-SB_RFI_vs_3bet.jpg"
mv "full-preflop-charts-14_2.jpg" "BTN_vs_SB-BB_3bet.jpg"
mv "full-preflop-charts-14_3.jpg" "SB_RFI_vs_BB_3bet.jpg"
